#include "trace_loader.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define INITIAL_CAPACITY 16

static int parse_group(const char *s, group_id_t *out) {
    if (strcmp(s, "SYSTEM") == 0)      { *out = GROUP_SYSTEM;      return 0; }
    if (strcmp(s, "INTERACTIVE") == 0) { *out = GROUP_INTERACTIVE; return 0; }
    if (strcmp(s, "BATCH") == 0)       { *out = GROUP_BATCH;       return 0; }
    if (strcmp(s, "IDLE") == 0)        { *out = GROUP_IDLE;        return 0; }
    return -1;
}

/* Sort key: arrival_tick ascending, pid ascending as a deterministic
   tie-break for same-tick arrivals (matches trace_gen.c's own tie-break,
   so traces generated by Phase 2 and traces loaded by Phase 3 agree on
   what "same-tick order" means). */
static int compare_by_arrival_pid(const void *a, const void *b) {
    process_t *const *pa = (process_t *const *)a;
    process_t *const *pb = (process_t *const *)b;
    if ((*pa)->arrival_tick != (*pb)->arrival_tick) {
        return (*pa)->arrival_tick - (*pb)->arrival_tick;
    }
    return (*pa)->pid - (*pb)->pid;
}

static void free_all(workload_t *w) {
    if (w->items != NULL) {
        for (int i = 0; i < w->count; i++) {
            process_destroy(w->items[i]);
        }
        free(w->items);
    }
    w->items = NULL;
    w->count = 0;
    w->capacity = 0;
}

int trace_loader_load(const char *path, workload_t *out) {
    out->items = NULL;
    out->count = 0;
    out->capacity = 0;

    FILE *f = fopen(path, "r");
    if (f == NULL) {
        fprintf(stderr, "trace_loader: cannot open '%s'\n", path);
        return -1;
    }

    char line[512];
    int line_no = 0;
    int header_checked = 0;

    while (fgets(line, sizeof(line), f) != NULL) {
        line_no++;

        /* strip trailing \n and/or \r */
        size_t len = strlen(line);
        while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) {
            line[--len] = '\0';
        }
        if (len == 0) {
            continue; /* skip blank lines silently — not malformed data,
                         just formatting whitespace */
        }

        if (!header_checked) {
            header_checked = 1;
            if (strcmp(line, "pid,arrival_tick,burst,group") == 0) {
                continue; /* recognized header row, not data — skip it */
            }
            /* else: not a header, fall through and parse this line as
               the first data row (headerless trace support) */
        }

        int pid = 0, arrival = 0, burst = 0;
        char group_str[64];
        int n = sscanf(line, "%d,%d,%d,%63s", &pid, &arrival, &burst, group_str);

        int bad = 0;
        const char *reason = "";
        group_id_t group = GROUP_SYSTEM; /* placeholder until validated */

        if (n != 4) {
            bad = 1; reason = "expected exactly 4 comma-separated fields (pid,arrival_tick,burst,group)";
        } else if (pid <= 0) {
            bad = 1; reason = "pid must be > 0";
        } else if (arrival < 0) {
            bad = 1; reason = "arrival_tick must be >= 0";
        } else if (burst <= 0) {
            bad = 1; reason = "burst must be > 0";
        } else if (parse_group(group_str, &group) != 0) {
            bad = 1; reason = "unrecognized group name (expected SYSTEM/INTERACTIVE/BATCH/IDLE)";
        }

        if (bad) {
            fprintf(stderr, "trace_loader: malformed row %d in '%s': \"%s\" (%s)\n",
                    line_no, path, line, reason);
            fclose(f);
            free_all(out);
            return -1;
        }

        if (out->count == out->capacity) {
            int new_cap = (out->capacity == 0) ? INITIAL_CAPACITY : out->capacity * 2;
            process_t **grown = (process_t **)realloc(out->items, sizeof(process_t *) * (size_t)new_cap);
            if (grown == NULL) {
                fprintf(stderr, "trace_loader: allocation failure growing workload array at row %d\n", line_no);
                fclose(f);
                free_all(out);
                return -1;
            }
            out->items = grown;
            out->capacity = new_cap;
        }

        process_t *p = process_create(pid, arrival, burst, group);
        if (p == NULL) {
            fprintf(stderr, "trace_loader: process_create() allocation failure at row %d\n", line_no);
            fclose(f);
            free_all(out);
            return -1;
        }
        out->items[out->count++] = p;
    }

    fclose(f);

    if (out->count > 1) {
        qsort(out->items, (size_t)out->count, sizeof(process_t *), compare_by_arrival_pid);
    }

    return 0;
}

void trace_loader_free(workload_t *w) {
    if (w == NULL) {
        return;
    }
    free_all(w);
}
